site_name: py_dummy_uds_server
site_url: https://chaitu-ycr.github.io/py_dummy_uds_server/
site_description: this is python project template description
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_dummy_uds_server
repo_url: https://github.com/chaitu-ycr/py_dummy_uds_server.git
edit_uri: blob/main/docs/

theme:
  name: readthedocs
  features:
    - toc.integrate

nav:
  - Overview: index.md
  - Reference: reference_manual.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
          setup_commands:
            - import sys
            - sys.path.append('./py_dummy_uds_server')
          selection:
            new_path_syntax: true
  - include-markdown:
      recursive: true
